name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight UTC
  workflow_dispatch:     # allows manual run from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Generate both light and dark snake SVGs
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: HoangHiu
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      # Push the generated files to the "output" branch
      - name: Push Snake to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
